// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    $("section.feedback .trigger").click(function() {
      $(this).hide();
      $("section.feedback form").slideDown(100);
      return $('html, body').animate({
        scrollTop: $("section.feedback").offset().top - 45
      }, 100);
    });
    $("section.contact-us .write-to-us").click(function(event) {
      event.preventDefault();
      $(this).hide();
      $("section.contact-us form").slideDown(100);
      return $('html, body').animate({
        scrollTop: $("section.contact-us form").offset().top - 50
      }, 100);
    });
    $("section.feedback form, section.contact-us form").submit(function(event) {
      event.preventDefault();
      if (window.confirm('Vill du se design av svarstexter till användaren?')) {
        return document.location = 'http://malmostad.github.io/wag/messages/';
      }
    });
    return $("article.body-copy form").submit(function(event) {
      event.preventDefault();
      if (window.confirm('Vill du se design av valideringsmeddelanden?')) {
        return document.location = 'http://malmostad.github.io/wag/forms/#form-validation';
      }
    });
  });

}).call(this);
