// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    $("section.feedback .trigger").click(function() {
      return $("section.feedback form").toggle();
    });
    $("section.feedback form").submit(function(event) {
      event.preventDefault();
      if (window.confirm('Vill du se design av svarstexter till användaren?')) {
        return document.location = 'http://malmostad.github.io/wag/messages/';
      }
    });
    return $("article.body-copy form").submit(function(event) {
      event.preventDefault();
      if (window.confirm('Vill du se design av valideringsmeddelanden?')) {
        return document.location = 'http://malmostad.github.io/wag/forms/#form-validation';
      }
    });
  });

}).call(this);
