// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    $("section.feedback .trigger").click(function() {
      $("section.feedback form").show();
      $('html, body').animate({
        scrollTop: $("section.feedback").offset().top - 45
      }, 100);
      return $(this).hide();
    });
    $("section.feedback form").submit(function(event) {
      event.preventDefault();
      if (window.confirm('Vill du se design av svarstexter till användaren?')) {
        return document.location = 'http://malmostad.github.io/wag/messages/';
      }
    });
    return $("article.body-copy form").submit(function(event) {
      event.preventDefault();
      if (window.confirm('Vill du se design av valideringsmeddelanden?')) {
        return document.location = 'http://malmostad.github.io/wag/forms/#form-validation';
      }
    });
  });

}).call(this);
